name: "Setup base"

runs:
  using: "composite"
  steps:
    - name: Setup base
      shell: bash
      run: |
        sed -i 's/SigLevel = Required DatabaseOptional/SigLevel = Optional TrustAll/' /etc/pacman.conf
        pacman --noconfirm --noprogressbar -Syyu
        pacman --noconfirm --noprogressbar -Sy \
          base-devel \
          git \
          gcc \
          make \
          grub \
          xorriso \
          nasm \
          mtools

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Mark directory as safe for git
      shell: bash
      run: git config --global --add safe.directory /__w/eth-os-com/eth-os-com
