name: Build Eth-OS

on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    name: "Build Eth-OS"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Check repository actions
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github/actions

      - name: Setup base
        uses: ./.github/actions/setup_base

      - name: Set variables
        shell: bash
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF$refs/heads/})" >> "$GITHUB_ENV"

      - name: Build Eth-OS
        run: |
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ethos-${{ github.branch }}-${{ github.sha_short }}
          path: out/iso/ethos.iso
          if-no-files-found: error
          retention-days: 90
